In [1]:
import numpy as np
list=[1,2,3,4]
nparray=np.array(list)
nparray

array([1, 2, 3, 4])

# info

In [19]:
#2d array
list1=[[1,2,3],[4,5,6]]
arrd=np.array(list1)

#converting str to any datatype to other datatype
arrdd=arrd.astype('float').astype('int')

#back to list
arrdd.tolist()


#shape
arrd.shape
#dtype
arrd.dtype

#num of dimesions 
arrd.ndim

#size
arrd.size


arrd

array([[1, 2, 3],
       [4, 5, 6]])

# Extracting Elements from array

In [ ]:
arrd


arrd[:2,:2]#extracting first elements from two rows and two colums
arrd[:2,:1]


# Boolean Indexing

In [24]:
b=arrd>3
b
#Elements which are greater than 4
arrd[b]

array([4, 5, 6])

# Reversing positions in array

In [37]:
arrd[::-1]
#using flip function


# rows flipping
np.flip(arrd,axis=0)

#columns flipping

np.flip(arrd,axis=1)





array([[6, 5, 4],
       [3, 2, 1]])

# Representing Missing Values

In [57]:

floatarr=arrd.astype('float64')
# floatarr.dtype
floatarr[1,1]=np.nan
floatarr[1,2]=np.inf

#Replacing missing values with -1

missing=np.isnan(floatarr)|np.isinf(floatarr)
floatarr[missing]=-1
floatarr

array([[ 1.,  2.,  3.],
       [ 4., -1., -1.]])

# Computing min,max,mean on ndarray

In [83]:
arrd.mean()
arrd.max()
arrd.min()

#column wise
column_min=np.amin(arrd,axis=0)
column_max=np.amax(arrd,axis=0)
column_mean=np.mean(arrd,axis=0)

#row_wise
row_min=np.amin(arrd,axis=1)
row_max=np.amax(arrd,axis=1)
row_mean=np.mean(arrd,axis=1)

#cummulative sum
np.cumsum(arrd)

arrd[0,1]=2
arrd

#copy function
arr_row=arrd[:1,:3].copy()
arr_row[0,1]=8
arr_row
arrd

array([[1, 8, 3]])

# Reshaping ndarray

In [86]:
arrd.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# creating sequences ,repetetions and random numbers using numpy

In [103]:
np.arange(5)
np.arange(0,10)
np.arange(10,0,-2)  #(start,end,difference)
np.linspace(10,0,8) 


#log
np.logspace(start=1,stop=50,num=10,base=10)

#zeros nd array

np.zeros([5,5])

#ones nd array
np.ones([3,2])



array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Creating repeating Sequences

In [105]:
l=[4,6,8]
np.tile(l,6) # here 6 as repeating number
np.tile(arrd,2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Generate Random Numbers

In [137]:
np.random.rand(3,4) #between o to 1
np.random.randn(2,2) #normal distribution mean=0 and varience =1
np.random.randint(0,10,size=[2,2]) #from 0 to 10
np.random.random() #one random number from 0 to 1
list=['a','e','i','o','u']
np.random.choice(list,size=9) #Pick 9 items from a given list, with equal probability
np.random.choice(list, size=10, p=[0.1, .3, 0.1, 0.4, 0.1])


#uniques

rn=np.random.RandomState(100)
ar=rn.randint(0,10,size=[2,2])
uniques=np.unique(ar)
counts=np.unique(ar,return_counts=True)
uniques
counts


(array([3, 7, 8]), array([1, 1, 2], dtype=int64))