#  Vital Functions for Data Analysis

In [11]:
import numpy as np

np.random.seed(100)
ar=np.random.randint(0,10,size=10)
#positions where elements are greater than 2
pos=np.where(ar>2) #positions
pos
elements=ar.take(pos) #elements
elements

#position of max and min values

np.argmax(ar)#postion max
np.argmin(ar)#position min

5

# data as a csv file

In [32]:
import pandas as pd
path='https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'


data = np.genfromtxt(path, delimiter=',' ,skip_header=1, filling_values=-999, dtype='float')
data1=np.genfromtxt(path, delimiter=',' ,skip_header=1,  dtype='object')
data1[:3]

# np.savetxt("out.csv",data,delimiter=',') # saving csv

array([[b'18', b'8', b'307', b'130', b'3504', b'12', b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', b'165', b'3693', b'11.5', b'70', b'1',
        b'"buick skylark 320"'],
       [b'18', b'8', b'318', b'150', b'3436', b'11', b'70', b'1',
        b'"plymouth satellite"']], dtype=object)

# Saving ndarray objects into file and load

In [33]:
np.save('myarray.npy',ar  #saving

In [34]:
lar=np.load('myarray.npy')  #loading
lar

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

# Concatenate two numpy arrays

In [49]:
np.random.seed(100)

ar1=np.random.randint(10,20,size=[3,3])

np.random.seed(100)

ar2=np.random.randint(0,10,size=[3,3])



#vertical Wise

arh=np.concatenate([ar1,ar2],axis=0)#method1 
np.vstack([ar1,ar2])# method2
np.r_[ar1,ar2]# method 3

#column Wise
np.concatenate([ar1,ar2],axis=1)#method1 
np.hstack([ar1,ar2])# method2
np.c_[ar1,ar2]# method 3
















array([[18, 18, 13,  8,  8,  3],
       [17, 17, 10,  7,  7,  0],
       [14, 12, 15,  4,  2,  5]])

# Sorting

In [69]:
# print(np.sort(arh,axis=0)) #column Wise SOrting
# print(np.sort(arh,axis=1))# row Wise Sorting



first_col=arh[:,0].argsort()  # sorting first column Ascending

arh[first_col]

arh[first_col[::-1]]  #descending order



first_row=arh[0,:].argsort() #sorting first row

arh[first_row]


#two or more columns or rows

lexsorted = np.lexsort((arh[:, 0], arh[:, 1])) #column 1 and 2
arh[lexsorted]


array([[ 4,  2,  5],
       [ 7,  7,  0],
       [ 8,  8,  3],
       [14, 12, 15],
       [17, 17, 10],
       [13, 18, 18]])

# Working with dates


In [86]:
dt=np.datetime64('2020-06-15')

as_string=np.datetime_as_string(dt)
min=np.timedelta64(54,'m')

# print("Adding 54 min:",dt+min)



# Sequence of dates
dates=np.arange(np.datetime64('2020-06-16'),np.datetime64('2020-06-30'))

np.is_busday(dates) #check if they are busy dates


dt1=dt.tolist()  # converting np.datetime64 to datetime.datetime
dt1.year  # year 
dt1.month # month
dt1.day # date
dt1.weekday() 




0

# Advanced numpy functions

In [98]:
def fun(x):
    if x%2==1:
        return x**2
    else:
        return x/2

# vectorization of numbers
fun_vec=np.vectorize(fun,otypes=[float])
fun_vec([10,15,20])   




np.random.seed(10)
newarr=np.random.randint(10,20,size=[5,5])
print(newarr)

#applying function row wise and column wise

col_wise=np.apply_along_axis(fun_vec,0,arr=newarr)
col_wise

[[19 14 10 11 19]
 [10 11 18 19 10]
 [18 16 14 13 10]
 [14 16 18 11 18]
 [14 11 13 16 15]]


array([[361.,   7.,   5., 121., 361.],
       [  5., 121.,   9., 361.,   5.],
       [  9.,   8.,   7., 169.,   5.],
       [  7.,   8.,   9., 121.,   9.],
       [  7., 121., 169.,   8., 225.]])

In [116]:
x=np.arange(10)
new_x=np.newaxis
x[:,new_x] #adding new column axis
x[new_x,:] #adding new row axis


# digitize
x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
for n in range(x.size):
    print(bins[inds[n]-1], "<=", x[n], "<", bins[inds[n]])


0.0 <= 0.2 < 1.0
4.0 <= 6.4 < 10.0
2.5 <= 3.0 < 4.0
1.0 <= 1.6 < 2.5


# Dot 

In [125]:
np.dot(3,4)
np.random.seed(100)
a1=np.random.randint(0,10,size=[2,2])
a2=np.random.randint(10,20,size=[2,2])
a1@a2 #@symbol is matmul
#or 
np.dot(a1,a2)



#trace of matrix

np.trace(a1)
#Or

15